name: narayavision_web
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_core: ^2.13.0
  cloud_firestore: 4.7.1
  firebase_auth: 4.6.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - lib/assets/
  uses-material-design: true

