name: narayavision_web
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  cloud_firestore: 4.7.1
  intl: 0.18.1
  image_picker: 0.8.9
  image_picker_windows: 0.2.1
  file_picker: 4.5.1
  firebase_core: 2.14.0
  firebase_auth: 4.6.3
  firebase_storage: 11.2.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - lib/assets/
  uses-material-design: true

